services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318"       # OTLP HTTP receiver
      - "8889:8889"       # Prometheus metrics endpoint
    depends_on:
      jaeger:
        condition: service_started
    networks:
      - otel-observability

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC (for Collector export)
    networks:
      - otel-observability
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"       # Loki API
    networks:
      - otel-observability
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"       # Prometheus UI
    depends_on:
      - otel-collector
    networks:
      - otel-observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"       # Grafana UI
    depends_on:
      - prometheus
      - jaeger
      - loki
      - otel-collector
    networks:
      - otel-observability

  cache:
    image: valkey/valkey:latest
    container_name: laborables-cache
    ports:
      - "6379:6379"
    networks:
      - otel-observability

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: dias-api
    environment:
      - LOG_LEVEL=INFO
      - CACHE_DB_HOST=cache
      - CACHE_DB_PORT=6379
      - CACHE_DB=0
      - OTEL_SERVICE_NAME=dias-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_METRICS_EXPORT_INTERVAL=5000
      - OTEL_PYTHON_LOG_LEVEL=INFO
    ports:
      - "8000:8000"       # FastAPI app
    depends_on:
      - otel-collector
      - cache
    networks:
      - otel-observability

networks:
  otel-observability:
    driver: bridge
