[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dias-api"
version = "1.0.0"
description = "API para calcular los dias laborables y mostrar los dias festivos según año y municipio español"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "fastapi[standard]>=0.116.1",
    "opentelemetry-distro>=0.65b0",
    "opentelemetry-exporter-otlp>=1.44.0",
    "opentelemetry-instrumentation-exceptions==0.65b0",
    "opentelemetry-instrumentation-fastapi==0.65b0",
    "opentelemetry-instrumentation-httpx==0.65b0",
    "opentelemetry-instrumentation-logging==0.65b0",
    "opentelemetry-instrumentation-redis>=0.65b0",
    "opentelemetry-instrumentation-requests==0.65b0",
    "opentelemetry-instrumentation-starlette==0.65b0",
    "opentelemetry-instrumentation-urllib3==0.65b0",
    "redis>=8.1.0",
    "requests>=2.32.5",
]

[tool.setuptools]
packages = ["app"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=6.0",
]
