name: Run reusable CI

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test-and-publish:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      image-name: dias-api
      dockerfile-path: ./dockerfile
